#!/bin/bash

# Author: twitter: @tamtam180 
# use sub-command: git,awk,sed,make,sleep,pidof,grep

arango_env_repo="git://github.com/triAGENS/ArangoDB.git"
arango_env_home="$(readlink -f "${ARANGO_ENV_HOME:-$HOME/.arango-env}")"
arango_env_config_file="${arango_env_home}/.default"
arango_env_git_dir="${arango_env_home}/git"
arango_env_install_dir="${arango_env_home}/arangodbs"
arango_env_version="0.4.1"
arango_env_current=""
arango_env_default=""

function __arango_env_prompt() {
  echo -ne "\e[1;31m$*\e[m"
  read YN
  if [ "$YN" == "y" ] || [ "$YN" == "Y" ]; then
    return 0
  fi
  return 1
}
function __arango_env_blue() {
  echo -e "\e[34m$*\e[m"
}
function __arango_env_green() {
  echo -e "\e[32m$*\e[m"
}
function __arango_env_yellow() {
  echo -e "\e[33m$*\e[m"
}
function __arango_env_info() {
  echo -e "\e[32m$*\e[m" 1>&2
}
function __arango_env_binfo() {
  echo -e "\e[34m$*\e[m" 1>&2
}
function __arango_env_warn() {
  echo -e "\e[33m$*\e[m" 1>&2
}
function __arango_env_error() {
  echo -e "\e[1;31m$*\e[m" 1>&2
}

function __arango_env_installed() {
  tag="$1"
  if [ "$tag" != "" ] && [ -d "${arango_env_install_dir}/$tag" ]; then
    return 0
  fi
  return 1
}

function __arango_env_get_pid() { # get pid from tag
  local tag="$1"
  local dir="${arango_env_install_dir}/${tag}"
  local pid_file="${dir}/var/run/arangod.pid"
  local pid=""
  [ -f "$pid_file" ] && pid="$(< "$pid_file")"
  echo -n "$pid"
  return 0
}

function __arango_env_load_default() {
  if [ -f "$arango_env_config_file" ]; then
    arango_env_default="$(< "$arango_env_config_file")"
    if [ "$arango_env_default" == "" ] ||  __arango_env_installed "$arango_env_default"; then
      return 0
    fi
    __arango_env_error "$arango_env_default is not installed"
    arango_env_default=""
  fi
  return 1
}

function __arango_env_save_default() {
  tag="$1"
  if [ "$tag" != "" ]; then
    arango_env_default="$tag"
  fi
  echo $arango_env_default> $arango_env_config_file
}

function __arango_env_update_path() {
  delpath="${arango_env_install_dir}/${arango_env_current}"
  addpath="${arango_env_install_dir}/$1/sbin:${arango_env_install_dir}/$1/bin"
  PATH=":${PATH}:"
  PATH="${PATH//:${delpath}:/:}"
  PATH="${PATH#:}"
  PATH="${PATH%:}"
  PATH="${addpath}:${PATH}"
  builtin hash -r
}

function __arango_env_command_install() {

  local RETVAL=0
  ( set -e
    tag=$1 
    if [ "$tag" == "" ]; then
      tag="master"
    fi

    if [ ! -d "$arango_env_git_dir" ] || [ ! -d "${arango_env_git_dir}/.git" ] ; then
      mkdir -p "$arango_env_git_dir"
      pushd "$arango_env_git_dir" > /dev/null
        git clone "$arango_env_repo" .
      popd > /dev/null
    fi

    # prompt
    if __arango_env_installed "$tag"; then
      __arango_env_prompt "overrite a ${tag}? (y/n) "
      YN=$?
      if [ $YN -ne 0 ]; then
        __arango_env_error "don't overwrite. bye."
        return 1
      fi
    fi

    pushd "$arango_env_git_dir" > /dev/null

      git checkout -f master
      git pull -f --all
      git checkout -f "${tag}"
      git clean -dxf 

      make setup > /dev/null
      ./configure \
        --prefix="${arango_env_install_dir}/${tag}" \
        --enable-all-in-one-libev \
        --enable-all-in-one-v8 \
        --enable-all-in-one-icu \
        --enable-mruby

      make clean > /dev/null
      make -j $(($(command -p getconf _NPROCESSORS_ONLN 2>/dev/null)+1)) > /dev/null
      RETVAL=$?
      if __arango_env_installed "$tag"; then
        make uninstall >/dev/null
      fi
      make install > /dev/null

      mkdir -p \
        "${arango_env_install_dir}/${tag}/tmp" \
        "${arango_env_install_dir}/${tag}/var/tmp" \
        "${arango_env_install_dir}/${tag}/var/run"

    popd > /dev/null
  )

  return $RETVAL

}

function __arango_env_check_running() {
  local pid="$1"

  if [ "$pid" == "" ]; then
    local current_dir="${arango_env_install_dir}/${arango_env_current}"
    local pid_file="${current_dir}/var/run/arangod.pid"
    [ -f "$pid_file" ] && pid="$(< "$pid_file")"
    [ "$pid" == "" ] && return 3
  fi

  local arangod_pid
  for arangod_pid in $(command pidof arangod); do
    if [ "$arangod_pid" == "$pid" ]; then
      return 0
    fi
  done
  return 3
}

function __arango_env_command_uninstall() {

  local tag="$1"
  [ "$tag" == "" ] && __arango_env_error "There are not enough arguments." && return 1

  if __arango_env_installed "$tag"; then
    local pid="$(__arango_env_get_pid "$tag")"
    if [ "$pid" != "" ] && __arango_env_check_running "$pid"; then
      __arango_env_command_stop "$tag"
    fi
    rm -fr "${arango_env_install_dir}/${tag}" 2>/dev/null
    __arango_env_info "Uninstall $tag done."
    return 0
  else
    __arango_env_error "$tag not found. listup installed versions."
    __arango_env_command_list
  fi
  return 1

}

function __arango_env_command_use() {

  local tag="$1"
  [ "$tag" == "" ] && __arango_env_error "There are not enough arguments." && return 1

  if ! __arango_env_installed "$tag"; then
    __arango_env_error "$tag is not installed"
    return 1
  fi

  arango_env_current="$tag"
  __arango_env_update_path "$tag"
  return 0

}

function __arango_env_command_default() {

  local tag="$1"
  [ "$tag" == "" ] && __arango_env_error "There are not enough arguments." && return 1

  if ! __arango_env_installed "$tag"; then
    __arango_env_error "$tag is not installed"
    return 1
  fi

  __arango_env_save_default "$tag"
  return 0

}

function __arango_env_command_list() {

  local opt="$1"
  local tags=""
  local itags="$([ -d "$arango_env_install_dir" ] && builtin echo $(command -p ls "$arango_env_install_dir"))"

  if [ "$opt" == "-a" ]; then
    tags="$(git ls-remote --tags $arango_env_repo | awk '{split($2,ary,"/");print ary[3]}') devel master"
  else
    tags="$itags"
  fi

  itags="::${itags// /::}::"
  local tag
  for tag in $tags; do
    local prefix="\ \ \ "
    local func
    if [ "$tag" == "$arango_env_default" ] && [ "$tag" == "$arango_env_current" ]; then
      prefix="\ \=\*"
      func="__arango_env_blue"
    elif [ "$tag" == "$arango_env_default" ]; then
      prefix="\ \ \*"
      func="__arango_env_green"
    elif [ "$tag" == "$arango_env_current" ]; then
      prefix="\ \=\>"
      func="__arango_env_blue"
    elif [[ $itags == *::$tag::* ]]; then  # installed
      func="__arango_env_yellow"
    else
      func="echo"
    fi
    eval $func "$prefix" "$tag"
  done

  __arango_env_warn ""
  __arango_env_warn "# => - current"
  __arango_env_warn "# =* - current && default"
  __arango_env_warn "#  * - default"
  __arango_env_warn ""

  return 0

}


function __arango_env_command_port() {
  local port="${1:-8529}"
  local tag="$2"
  [ "$tag" == "" ] && tag="$arango_env_current"

  local RETVAL=0
  if [ "$tag" != "" ] && __arango_env_installed "$tag"; then
    if [[ "$port" =~ ^[0-9]+$ ]]; then
      local dir="${arango_env_install_dir}/${tag}/etc/arangodb"
      sed -i -e "s/^\(endpoint\s*=\s*\)\(.*\):\([0-9]\+\)\s*$/\1\2:${port}/g" $dir/*.conf
      if __arango_env_check_running; then
        __arango_env_info "Restart arangod!"
        __arango_env_command_restart "$tag"
        RETVAL=$?
      fi
    else
      __arango_env_error "Invalid arguments: $port"
      RETVAL=1
    fi
  fi
  return $RETVAL
}

function __arango_env_command_status() {

  local tag="$1"
  local itags

  if [ "$tag" == "" ]; then # ALL
    itags="$([ -d "$arango_env_install_dir" ] && builtin echo $(command -p ls "$arango_env_install_dir"))"
  else
    itags=$tag
  fi

  local RETVAL
  local itag
  for itag in $itags; do
    local dir="${arango_env_install_dir}/${itag}"
    local pid_file="${dir}/var/run/arangod.pid"
    local pid=""
    [ ! -d "${arango_env_install_dir}/$itag" ] && return 3
    [ -f "$pid_file" ] && pid="$(< "$pid_file")"
    if [ "$pid" != "" ]; then
      __arango_env_check_running "$pid"
      RETVAL=$?
    else
      RETVAL=3
    fi

    local port
    local conf_file="${arango_env_install_dir}/${itag}/etc/arangodb/arangod.conf"
    [ -f "$conf_file" ] && port=$(sed -ne "s/^\(endpoint\s*=\s*\)\(.*\):\([0-9]\+\)\s*$/\3/p" "${conf_file}")

    case $RETVAL in
      0) __arango_env_info  "[${itag}] (port=${port}) running. pid=${pid}" ;;
      3) __arango_env_warn  "[${itag}] (port=${port}) not running." ;;
      *) __arango_env_error "[${itag}] (port=${port}) unhandling status code: $RETVAL.";;
    esac
  done
  return $RETVAL

}

function __arango_env_command_start() {

  local tag="$1"
  [ "$tag" == "" ] && tag="${arango_env_current}"

  local dir="${arango_env_install_dir}/${tag}"
  local pid_file="${dir}/var/run/arangod.pid"

  local start_opt_ext=""
  if [ "$tag" == "master" ] || [ "$tag" == "devel" ] ||  [ "$tag" ">" "v1.3" ] || [ "$tag" == "v1.3" ]; then
    start_opt_ext=" --temp-path=\"${dir}/tmp\""
  fi

  ${dir}/sbin/arangod \
    --daemon \
    --pid="${pid_file}" \
    --working-directory="${dir}/var/tmp" \
    $start_opt_ext

  local RETVAL=$?
  local RETVAL2=$RETVAL
  local pid="$(< "${pid_file}" )"
  # Avoid issue 546
  local i
  for i in {1..3}; do
    if __arango_env_check_running "$pid"; then
      RETVAL2=0
      sleep 1  # no break, because port duplicated
    else
      RETVAL2=1
      break
    fi
  done

  if [ $RETVAL2 -eq 0 ]; then
    __arango_env_info "[${tag}] Start success! pid=${pid}"
  else
    __arango_env_error "[${tag}] Start failed: exit-code=${RETVAL}"
    RETVAL=$RETVAL2
  fi

  return $RETVAL
}

function __arango_env_command_stop() {

  local tag="$1"
  [ "$tag" == "" ] && tag="${arango_env_current}"

  local RETVAL=0
  local current_dir="${arango_env_install_dir}/${tag}"
  local pid_file="${current_dir}/var/run/arangod.pid"

  if [ -f "$pid_file" ]; then
    local pid="$(< "$pid_file")"
    if [[ "$pid" =~ ^[0-9]+$ ]]; then
      if __arango_env_check_running "$pid"; then
        builtin kill -TERM $pid >/dev/null 2>&1
        local i
        for i in {1..60}; do
          if __arango_env_check_running "$pid"; then
            echo -n "." 1>&2
            sleep 1
          else
            __arango_env_info "\n[${tag}] Stop Success!"
            break
          fi
        done
        if [ $i -ge 60 ]; then
          __arango_env_warn "\n[${tag}] Stop failure. arangod still running. force kill. pid=${pid}"
          builtin kill -KILL $pid >/dev/null 2>&1
        fi
      else
        __arango_env_warn "[${tag}] Process still dead, but pid-file existed. pid=${pid}"
        RETVAL=1
      fi
    fi
    #rm -f "$pid_file"
  fi
  return $RETVAL
}

function __arango_env_command_restart() {
  local tag="$1"
  __arango_env_command_stop "$tag"
  __arango_env_command_start "$tag"
  return $?
}

function __arango_env_command_version() {
  __arango_env_info "version: ${arango_env_version}"
}

function __arango_env_command_info() {
  __arango_env_warn  " directory = $arango_env_home"
  __arango_env_info  " - default = $arango_env_default"
  __arango_env_binfo " - current = $arango_env_current"
}

function __arango_env_command_help() {
  msg=$(cat <<_EOS_

  usage arango-env [install|uninstall|use|default|list|port|info|start|stop|restart|status|help]

    - install [version]         Install ArangoDB
                                set version to "master" if empty.
    - uninstall [version]       Uninstall ArangoDB
    - use [version]             Change current version.
    - default [version]         Set default version.
    - list [-a]                 Listup installed version.
                                -a option is listup ALL available version. (include not install).
    - port [portnum] [version]  Change configure a port number of current version.
                                if not specify portnum, use 8529 as default.
                                if not specify version, target a current version.
    - info                      Display current version and default version.
    - start [version]           Start arangod of current version.
    - stop [version]            Stop arangod of current version.
    - restart [version]         Restart arangod of current version.
    - status [version]          Display process status of current version.
    - version                   Display version.
    - help                      Display help.
\n
_EOS_
  )
  __arango_env_warn "$msg"
  return 0
}


# execute command
function arango-env() {

  __arango_env_load_default

  cmd="$1"
  shift
  case "$cmd" in
    "install") __arango_env_command_install $@ ;;
    "uninstall") __arango_env_command_uninstall $@ ;;
    "use") __arango_env_command_use $@ ;;
    "default") __arango_env_command_default $@ ;;
    "list") __arango_env_command_list $@ ;;
    "port" ) __arango_env_command_port $@ ;;
    "status") __arango_env_command_status $@ ;;
    "start") __arango_env_command_start $@ ;;
    "stop") __arango_env_command_stop $@ ;;
    "restart") __arango_env_command_restart $@ ;;
    "help") __arango_env_command_help ;;
    "info") __arango_env_command_info ;;
    "version") __arango_env_command_version ;;
    *) __arango_env_command_help ; __arango_env_command_info ;;
  esac
}

# load current configure
__arango_env_load_default
arango_env_current="$arango_env_default"

# direct running (but cannot change PATH environment)
if [ "$1" != "" ]; then
  arango-env $@
fi


